version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: release-fast-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: release_fast
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - release-fast-network

volumes:
  postgres_data:

networks:
  release-fast-network:
    driver: bridge
